# Generated by Django 4.2.1 on 2024-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabletime',
            old_name='day_of_week',
            new_name='from_day',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='to_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default=True, max_length=10, null=True),
        ),
    ]
