# Generated by Django 4.2.1 on 2024-10-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_day_of_week_availabletime_from_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='slug',
        ),
    ]
